// 1
export const stage1__mob3e = patch(stage1__mob3, {
  VOIDS_COUNT: 1700,
  AGRO_D: 5,
  RUN_D: 30,
  HIT_D: [0, 360],
  HIT_VER: 0.9,
  MOVE_VER: 0.5,
  MOVE_TIME: [0.5, 1],
  LONG_MOVE_VER: 0.5,
  LONG_MOVE_TIME: [1, 2],
  STOP_TIME: [0, 0.5],

  ROLL_TIME: [30, 60],
  JUMP_TIME: [30, 60],
  FIGHTER: {
    LANG_RU: 'Грех Гнева',
    name: 'stage1__mob3e',
    hitSpeed: 1.5,
    moveTimeF: 1,
    BALANCE: 100,
    SCALE: 1.5,
    ACC: 100,
    RUN_ACC: 400,
    damage: 40,
    HP: 400,
  },
  rightHand: {
    type: 'weapon',
    kind: 'stage1__mob3e__rightHand',
    bodyScale: 1,
    balance: 10,
    staminaUse: 16,
    staminaUseTime: 1,
    stunTime: 1,
  },
  leftHand: {
    type: 'weapon',
    kind: 'stage1__mob3e__leftHand',
    bodyScale: 1,
  },
});
// 2
export const stage1__mob3e2 = patch(stage1__mob3, {
  VOIDS_COUNT: 1700,
  AGRO_D: 5,
  RUN_D: 30,
  HIT_D: [0, 360],
  HIT_VER: 0.9,
  MOVE_VER: 0.5,
  MOVE_TIME: [0.5, 1],
  LONG_MOVE_VER: 0.5,
  LONG_MOVE_TIME: [1, 2],
  STOP_TIME: [0, 0.5],

  ROLL_TIME: [30, 60],
  JUMP_TIME: [30, 60],
  FIGHTER: {
    LANG_RU: 'Грех Гордыни',
    name: 'stage1__mob3e2',
    hitSpeed: 1,
    moveTimeF: 1,
    BALANCE: 100,
    SCALE: 1,
    ACC: 100,
    RUN_ACC: 400,
    damage: 50,
    HP: 400,
  },
  rightHand: {
    type: 'weapon',
    kind: 'stage1__mob3e2__rightHand',
    bodyScale: 1.5,
    balance: 10,
    staminaUse: 16,
    staminaUseTime: 1,
    stunTime: 1,
  },
  leftHand: {
    type: 'weapon',
    kind: 'stage1__mob3e2__leftHand',
    bodyScale: 1.5,
  },
});
// 3
export const stage1__mob3e3 = patch(stage1__mob3, {
  VOIDS_COUNT: 3000,
  AGRO_D: 5,
  RUN_D: 30,
  HIT_D: [0, 360],
  HIT_VER: 0.9,
  MOVE_VER: 0.5,
  MOVE_TIME: [0.5, 1],
  LONG_MOVE_VER: 0.5,
  LONG_MOVE_TIME: [1, 2],
  STOP_TIME: [0, 0.5],

  ROLL_TIME: [30, 60],
  JUMP_TIME: [30, 60],
  FIGHTER: {
    LANG_RU: 'Тяжкий Грех',
    name: 'stage1__mob3e3',
    hitSpeed: 3,
    moveTimeF: 1,
    BALANCE: 150,
    SCALE: 2,
    ACC: 100,
    RUN_ACC: 300,
    damage: 30,
    HP: 400,
  },
  rightHand: {
    type: 'weapon',
    kind: 'stage1__mob3e3__rightHand',
    bodyScale: 1.5,
    balance: 20,
    staminaUse: 16,
    staminaUseTime: 1,
    stunTime: 1,
  },
  leftHand: {
    type: 'weapon',
    kind: 'stage1__mob3e3__leftHand',
    bodyScale: 1.5,
  },
});
// 4
export const stage1__mob3e4 = patch(stage1__mob3, {
  VOIDS_COUNT: 2000,
  AGRO_D: 5,
  RUN_D: 30,
  HIT_D: [0, 360],
  HIT_VER: 0.9,
  MOVE_VER: 0.5,
  MOVE_TIME: [0.5, 1],
  LONG_MOVE_VER: 0.5,
  LONG_MOVE_TIME: [1, 2],
  STOP_TIME: [0, 0.5],

  ROLL_TIME: [30, 60],
  JUMP_TIME: [30, 60],
  FIGHTER: {
    LANG_RU: 'Обыденный Грех',
    name: 'stage1__mob3e4',
    hitSpeed: 3,
    moveTimeF: 1,
    BALANCE: 100,
    SCALE: 1,
    ACC: 100,
    RUN_ACC: 300,
    damage: 20,
    HP: 200,
  },
  rightHand: {
    type: 'weapon',
    kind: 'stage1__mob3e4__rightHand',
    bodyScale: 1.5,
    balance: 20,
    staminaUse: 16,
    staminaUseTime: 1,
    stunTime: 1,
  },
  leftHand: {
    type: 'weapon',
    kind: 'stage1__mob3e4__leftHand',
    bodyScale: 1.5,
  },
});
// 5
export const stage1__mob3e5 = patch(stage1__mob3, {
  VOIDS_COUNT: 5000,
  AGRO_D: 7,
  RUN_D: 30,
  HIT_D: [0, 360],
  HIT_VER: 0.9,
  MOVE_VER: 0.5,
  MOVE_TIME: [0.5, 1],
  LONG_MOVE_VER: 0.5,
  LONG_MOVE_TIME: [1, 2],
  STOP_TIME: [0, 0.5],

  ROLL_TIME: [30, 60],
  JUMP_TIME: [30, 60],
  FIGHTER: {
    LANG_RU: 'Демон',
    name: 'stage1__mob3e5',
    hitSpeed: 5,
    moveTimeF: 1,
    BALANCE: 100,
    SCALE: 1.5,
    ACC: 100,
    RUN_ACC: 300,
    damage: 80,
    HP: 800,
  },
  rightHand: {
    type: 'weapon',
    kind: 'stage1__mob3e5__rightHand',
    bodyScale: 2,
    balance: 10,
    staminaUse: 16,
    staminaUseTime: 1,
    stunTime: 1,
  },
  leftHand: {
    type: 'weapon',
    kind: 'stage1__mob3e5__leftHand',
    bodyScale: 2,
  },
});
// boss1
export const stage1__mob3e__boss1 = patch(stage1__mob3, {
  IS_BOSS: true,
  VOIDS_COUNT: 30000,
  AGRO_D: 10,
  RUN_D: 30,
  HIT_D: [0, 400],
  HIT_VER: 0.8,
  MOVE_VER: 0.5,
  MOVE_TIME: [0.5, 1],
  LONG_MOVE_VER: 0.5,
  LONG_MOVE_TIME: [1, 2],
  STOP_TIME: [0, 0.5],

  ROLL_TIME: [30, 60],
  JUMP_TIME: [30, 60],
  FIGHTER: {
    LANG_RU: 'Первый Грех',
    name: 'stage1__mob3e__boss1',
    hitSpeed: 2,
    SCALE: 3,
    damage: 50,
    BALANCE: 200,
    STAMINA: 1000,
    HP: 4000,
    ACC: 100,
    RUN_ACC: 1000,
  },
  rightHand: {
    type: 'weapon',
    kind: 'stage1__mob3e__boss1__rightHand',
    bodyScale: 1.4,
    staminaUse: 10,
    staminaUseTime: 1,
    stunTime: 0.5,
  },
  leftHand: {
    type: 'weapon',
    kind: 'stage1__mob3e__boss1__leftHand',
    bodyScale: 1.4,
  },
});