// 1
export const stage1__mob3b = patch(stage1__mob3, {
  VOIDS_COUNT: 700,
  AGRO_D: 5,
  RUN_D: 30,
  HIT_D: [0, 360],
  HIT_VER: 0.9,
  MOVE_VER: 0.5,
  MOVE_TIME: [0.5, 1],
  LONG_MOVE_VER: 0.5,
  LONG_MOVE_TIME: [1, 2],
  STOP_TIME: [0, 0.5],

  ROLL_TIME: [30, 60],
  JUMP_TIME: [30, 60],
  FIGHTER: {
    LANG_RU: 'Грех Сладострастия',
    name: 'stage1__mob3b',
    hitSpeed: 2,
    moveTimeF: 0.5,
    BALANCE: 60,
    SCALE: 1,
    ACC: 100,
    RUN_ACC: 500,
    damage: 30,
    HP: 300,
  },
  rightHand: {
    type: 'weapon',
    kind: 'stage1__mob3b__rightHand',
    bodyScale: 1.5,
    balance: 10,
    staminaUse: 16,
    staminaUseTime: 0.3,
    stunTime: 1.5,
  },
  leftHand: {
    type: 'weapon',
    kind: 'stage1__mob3b__leftHand',
    bodyScale: 1.5,
  },
});
// 2
export const stage1__mob3b2 = patch(stage1__mob3, {
  VOIDS_COUNT: 800,
  AGRO_D: 6,
  RUN_D: 30,
  HIT_D: [0, 360],
  HIT_VER: 0.9,
  MOVE_VER: 0.5,
  MOVE_TIME: [0.5, 1],
  LONG_MOVE_VER: 0.5,
  LONG_MOVE_TIME: [1, 2],
  STOP_TIME: [0, 0.5],

  ROLL_TIME: [30, 60],
  JUMP_TIME: [30, 60],
  FIGHTER: {
    LANG_RU: 'Грех Зависти',
    name: 'stage1__mob3b2',
    hitSpeed: 1,
    moveTimeF: 0.5,
    BALANCE: 60,
    SCALE: 1,
    ACC: 100,
    RUN_ACC: 500,
    damage: 30,
    HP: 200,
  },
  rightHand: {
    type: 'weapon',
    kind: 'stage1__mob3b2__rightHand',
    bodyScale: 1.5,
    balance: 10,
    staminaUse: 16,
    staminaUseTime: 0.3,
    stunTime: 1.5,
  },
  leftHand: {
    type: 'weapon',
    kind: 'stage1__mob3b2__leftHand',
    bodyScale: 1.5,
  },
});