// 1
export const stage1__mob1e = patch(stage1__mob1, {
  VOIDS_COUNT: 2200,
  AGRO_D: 7,
  RUN_D: 30,
  HIT_D: [0, 300],
  HIT_VER: 0.8,
  MOVE_VER: 0.5,
  MOVE_TIME: [0.5, 1],
  LONG_MOVE_VER: 0.5,
  LONG_MOVE_TIME: [1, 2],
  STOP_TIME: [0, 0.5],

  ROLL_TIME: [30, 60],
  JUMP_TIME: [30, 60],
  FIGHTER: {
    LANG_RU: 'Огненный Элемент',
    name: 'stage1__mob1e',
    hitSpeed: 2,
    SCALE: 1,
    damage: 50,
    BALANCE: 80,
    HP: 300,
    ACC: 100,
    RUN_ACC: 800,
  },
  rightHand: {
    type: 'weapon',
    kind: 'stage1__mob1e__rightHand',
    bodyScale: 1.2,
    balance: 10,
    staminaUse: 10,
    staminaUseTime: 2,
    stunTime: 0.5,
  },
  leftHand: {
    type: 'weapon',
    kind: 'stage1__mob1e__leftHand',
    bodyScale: 1.2,
  },
});
// 2
export const stage1__mob1e2 = patch(stage1__mob1, {
  VOIDS_COUNT: 3200,
  AGRO_D: 6,
  RUN_D: 30,
  HIT_D: [0, 300],
  HIT_VER: 0.8,
  MOVE_VER: 0.5,
  MOVE_TIME: [0.5, 1],
  LONG_MOVE_VER: 0.5,
  LONG_MOVE_TIME: [1, 2],
  STOP_TIME: [0, 0.5],

  ROLL_TIME: [30, 60],
  JUMP_TIME: [30, 60],
  FIGHTER: {
    LANG_RU: 'Элементаль Огня',
    name: 'stage1__mob1e2',
    hitSpeed: 3,
    SCALE: 1.5,
    damage: 70,
    BALANCE: 140,
    HP: 500,
    ACC: 100,
    RUN_ACC: 800,
  },
  rightHand: {
    type: 'weapon',
    kind: 'stage1__mob1e2__rightHand',
    bodyScale: 1.2,
    balance: 10,
    staminaUse: 10,
    staminaUseTime: 2,
    stunTime: 0.5,
  },
  leftHand: {
    type: 'weapon',
    kind: 'stage1__mob1e2__leftHand',
    bodyScale: 1.24,
  },
});
// 3
export const stage1__mob1e3 = patch(stage1__mob1, {
  VOIDS_COUNT: 1900,
  AGRO_D: 7,
  RUN_D: 30,
  HIT_D: [0, 300],
  HIT_VER: 0.8,
  MOVE_VER: 0.5,
  MOVE_TIME: [0.5, 1],
  LONG_MOVE_VER: 0.5,
  LONG_MOVE_TIME: [1, 2],
  STOP_TIME: [0, 0.5],

  ROLL_TIME: [30, 60],
  JUMP_TIME: [30, 60],
  FIGHTER: {
    LANG_RU: 'Элемент Земли',
    name: 'stage1__mob1e3',
    hitSpeed: 3,
    SCALE: 1.5,
    damage: 60,
    BALANCE: 80,
    HP: 700,
    ACC: 100,
    RUN_ACC: 400,
  },
  rightHand: {
    type: 'weapon',
    kind: 'stage1__mob1e3__rightHand',
    bodyScale: 1.4,
    balance: 10,
    staminaUse: 10,
    staminaUseTime: 2,
    stunTime: 0.5,
  },
  leftHand: {
    type: 'weapon',
    kind: 'stage1__mob1e3__leftHand',
    bodyScale: 1.4,
  },
});
// 4
export const stage1__mob1e4 = patch(stage1__mob1, {
  VOIDS_COUNT: 1900,
  AGRO_D: 7,
  RUN_D: 30,
  HIT_D: [0, 300],
  HIT_VER: 0.8,
  MOVE_VER: 0.5,
  MOVE_TIME: [0.5, 1],
  LONG_MOVE_VER: 0.5,
  LONG_MOVE_TIME: [1, 2],
  STOP_TIME: [0, 0.5],

  ROLL_TIME: [30, 60],
  JUMP_TIME: [30, 60],
  FIGHTER: {
    LANG_RU: 'Земляная Элементаль',
    name: 'stage1__mob1e4',
    hitSpeed: 4,
    SCALE: 2,
    damage: 60,
    BALANCE: 80,
    HP: 1000,
    ACC: 100,
    RUN_ACC: 400,
  },
  rightHand: {
    type: 'weapon',
    kind: 'stage1__mob1e4__rightHand',
    bodyScale: 1.6,
    balance: 10,
    staminaUse: 10,
    staminaUseTime: 2,
    stunTime: 0.5,
  },
  leftHand: {
    type: 'weapon',
    kind: 'stage1__mob1e4__leftHand',
    bodyScale: 1.6,
  },
});